// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGy3L5CRmrRC0bvDsvys0vXR04V1-mVhI',
    appId: '1:388233580989:web:5add78c452b10f018c42d4',
    messagingSenderId: '388233580989',
    projectId: 'donatekart-42dd6',
    authDomain: 'donatekart-42dd6.firebaseapp.com',
    storageBucket: 'donatekart-42dd6.firebasestorage.app',
    measurementId: 'G-B4NEDM1TTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLIoVc7sgqG7Bysvbq_A_JrixfGh4hGU',
    appId: '1:388233580989:android:1b6f19d9176eeb2f8c42d4',
    messagingSenderId: '388233580989',
    projectId: 'donatekart-42dd6',
    storageBucket: 'donatekart-42dd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChb79gRkMTVM00gEaLIRIIIp685YSEjG0',
    appId: '1:388233580989:ios:572634c295dcc6698c42d4',
    messagingSenderId: '388233580989',
    projectId: 'donatekart-42dd6',
    storageBucket: 'donatekart-42dd6.firebasestorage.app',
    iosBundleId: 'com.example.donateKart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChb79gRkMTVM00gEaLIRIIIp685YSEjG0',
    appId: '1:388233580989:ios:572634c295dcc6698c42d4',
    messagingSenderId: '388233580989',
    projectId: 'donatekart-42dd6',
    storageBucket: 'donatekart-42dd6.firebasestorage.app',
    iosBundleId: 'com.example.donateKart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGy3L5CRmrRC0bvDsvys0vXR04V1-mVhI',
    appId: '1:388233580989:web:03fbfe4bd5b823e88c42d4',
    messagingSenderId: '388233580989',
    projectId: 'donatekart-42dd6',
    authDomain: 'donatekart-42dd6.firebaseapp.com',
    storageBucket: 'donatekart-42dd6.firebasestorage.app',
    measurementId: 'G-C0C5QSQ1Q7',
  );
}
